// <auto-generated />
using System;
using ATM_EfCore_CodeFirst.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ATM_EfCore_CodeFirst.Migrations
{
    [DbContext(typeof(Bank_CustDbContext))]
    [Migration("20230808163158_TransMigration")]
    partial class TransMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ATM_EfCore_CodeFirst.Models.Bank_CustomersModel", b =>
                {
                    b.Property<int>("AccountNumber")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AccountNumber"));

                    b.Property<double>("Balance")
                        .HasColumnType("float");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("MobileNumber")
                        .HasColumnType("bigint");

                    b.Property<int>("PinNumber")
                        .HasColumnType("int");

                    b.HasKey("AccountNumber");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("ATM_EfCore_CodeFirst.Models.TransationModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AccountNumber")
                        .HasColumnType("int");

                    b.Property<string>("Amount")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Bank_CustomersAccountNumber")
                        .HasColumnType("int");

                    b.Property<DateTime>("Trans_Time")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Bank_CustomersAccountNumber");

                    b.ToTable("Transations");
                });

            modelBuilder.Entity("ATM_EfCore_CodeFirst.Models.TransationModel", b =>
                {
                    b.HasOne("ATM_EfCore_CodeFirst.Models.Bank_CustomersModel", "Bank_Customers")
                        .WithMany("Transations")
                        .HasForeignKey("Bank_CustomersAccountNumber")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bank_Customers");
                });

            modelBuilder.Entity("ATM_EfCore_CodeFirst.Models.Bank_CustomersModel", b =>
                {
                    b.Navigation("Transations");
                });
#pragma warning restore 612, 618
        }
    }
}
